import React, { useState } from 'react'
import { motion, AnimatePresence } from 'framer-motion'
import { Wallet, Check, ArrowRight, AlertTriangle, Info } from 'lucide-react'

export default function Pricing({ onNavigate }) {
  const [openFaq, setOpenFaq] = useState(null)

  const toggleFaq = (index) => {
    setOpenFaq(prev => (prev === index ? null : index))
  }

  const faqs = [
    {
      q: "If AiBizzApp is free and open-source, how do you make money?",
      a: "AiBizzApp is 100% free and open-source software. Revenue is generated by providing AiBizz Cloud managed hosting, enterprise-grade infrastructure, automated security updates, backups, Product Warranty, Priority SLA support, and official implementation consulting."
    },
    {
      q: "Do you have paid features hidden behind paywalls?",
      a: "No. All modules and features in AiBizzApp—Accounting, CRM, Stock, Manufacturing, HR, Projects, POS, and more—are completely open and free with no artificial paywalls or feature gating. You only pay for hosting and cloud infrastructure resources."
    },
    {
      q: "Does AiBizz provide implementation services?",
      a: "Yes. AiBizz and its global certified network of 200+ partners provide full implementation, onboarding, data migration, and customization services. You can also self-implement using our free documentation or opt for quick Starter Packs."
    },
    {
      q: "How does AiBizz Cloud billing work?",
      a: "AiBizz Cloud bills based on the compute and server resources your instance utilizes (such as CPU, RAM, and database storage), not per user. You can have unlimited user logins on your plan."
    },
    {
      q: "What is Product Warranty?",
      a: "Product Warranty guarantees that bugs and issues in core AiBizzApp software are prioritized and resolved by the core engineering team, along with managed upgrades ensuring high platform reliability."
    },
    {
      q: "What is Priority SLA?",
      a: "Priority SLA gives your enterprise direct access to dedicated senior engineers with guaranteed response times under 1 hour for critical production incidents, available 24/7/365."
    },
    {
      q: "Do you have discounts for education institutes and non-profits?",
      a: "Yes, we offer generous discounts and sponsored hosting credits for accredited educational institutions, schools, non-profit organizations, and social enterprises."
    }
  ]

  return (
    <div className="pt-28 pb-20 bg-white text-slate-900 selection:bg-amber-400 selection:text-slate-950 min-h-screen">
      <div className="max-w-4xl mx-auto px-4 sm:px-6 lg:px-8">
        
        {/* Top Header Card */}
        <div className="mb-14 text-left">
          <div className="flex items-start gap-4">
            <div className="p-3 rounded-2xl bg-slate-100 text-slate-700 mt-1 shrink-0 border border-slate-200 shadow-sm">
              <Wallet className="w-7 h-7 text-slate-700" />
            </div>
            <div>
              <h1 className="text-3xl sm:text-4xl font-medium text-slate-900 tracking-tight">
                Want to start using AiBizzApp?
              </h1>
              <p className="mt-3 text-sm sm:text-base text-slate-600 leading-relaxed max-w-2xl">
                Your cost will include two components - <strong className="text-slate-900 font-semibold">Hosting</strong> and <strong className="text-slate-900 font-semibold">Implementation</strong>. AiBizzApp is free and open-source, but needs to be hosted on cloud. Cloud providers charge a Hosting fee. Once hosting is decided, you can either start with the default setup or hire an AiBizz partner for implementation.
              </p>
            </div>
          </div>
        </div>

        {/* STEP 1: Host your site on AiBizz Cloud */}
        <div className="relative pl-8 sm:pl-12 border-l-2 border-slate-200 pb-16">
          {/* Step 1 badge */}
          <div className="absolute -left-[17px] top-0 h-8 w-8 rounded-full bg-slate-100 border-2 border-slate-300 text-slate-700 flex items-center justify-center text-xs font-bold shadow-sm">
            1
          </div>

          <div>
            <span className="text-[11px] font-bold tracking-wider text-slate-400 uppercase">
              STEP 1
            </span>
            <h2 className="text-2xl font-medium text-slate-900 tracking-tight mt-1">
              Host your site on AiBizz Cloud
            </h2>
            <p className="mt-2 text-sm sm:text-base text-slate-600 leading-relaxed">
              <strong className="text-slate-900 font-semibold">AiBizz Cloud is AiBizz's own managed hosting platform</strong> for simple, reliable, and secure hosting of applications like AiBizzApp. It eliminates the complexities of installation, setup, upgrading, monitoring, and maintenance.
            </p>
            <p className="mt-3 text-sm sm:text-base text-slate-600">
              Pick a plan that best suits your needs, and <strong className="text-slate-900 font-semibold">pay only for what you use</strong>, and not per user!
            </p>

            {/* Hosting Plans Grid: Sites vs Servers */}
            <div className="grid grid-cols-1 md:grid-cols-2 gap-6 mt-8">
              
              {/* Plan 1: Sites */}
              <div className="rounded-2xl border border-slate-200/90 bg-white p-6 sm:p-7 shadow-sm hover:shadow-xl hover:border-slate-300 transition-all flex flex-col justify-between">
                <div>
                  <div className="flex items-center justify-between">
                    <h3 className="text-xl font-bold text-slate-900">Application</h3>
                    <span className="text-[11px] font-semibold text-slate-500 bg-slate-100 px-2.5 py-0.5 rounded-full">Shared</span>
                  </div>
                  <p className="text-xs sm:text-sm text-slate-500 mt-1">
                    Start small and run a single site with multiple apps on shared servers
                  </p>

                  <div className="mt-6 flex items-baseline gap-1">
                    <span className="text-3xl font-bold text-slate-900">$12</span>
                    <span className="text-xs text-slate-500 font-medium">onwards /mo</span>
                  </div>

                  {/* Cloud logos */}
                  <div className="flex items-center gap-3 mt-4 text-[11px] font-bold text-slate-500">
                    <span className="text-amber-600 font-black">aws</span>
                    <span className="text-rose-600 font-black">OCI</span>
                    <span className="text-red-600 font-black tracking-wider">HETZNER</span>
                  </div>

                  {/* Checklist */}
                  <ul className="mt-6 space-y-3 text-xs sm:text-sm text-slate-600 border-t border-slate-100 pt-5">
                    <li className="flex items-center gap-2.5">
                      <Check className="w-4 h-4 text-[#0066cc] shrink-0" />
                      <span>Single site</span>
                    </li>
                    <li className="flex items-center gap-2.5">
                      <Check className="w-4 h-4 text-[#0066cc] shrink-0" />
                      <span>Managed upgrades & backups</span>
                    </li>
                    <li className="flex items-center gap-2.5">
                      <Check className="w-4 h-4 text-[#0066cc] shrink-0" />
                      <span>Lowest entry cost</span>
                    </li>
                    <li className="flex items-center gap-2.5">
                      <Check className="w-4 h-4 text-[#0066cc] shrink-0" />
                      <span>Scripting & custom apps</span>
                      <Info className="w-3.5 h-3.5 text-slate-400" />
                    </li>
                    <li className="flex items-center gap-2.5">
                      <Check className="w-4 h-4 text-[#0066cc] shrink-0" />
                      <span>Product Warranty</span>
                      <Info className="w-3.5 h-3.5 text-slate-400" />
                    </li>
                    <li className="flex items-center gap-2.5 text-slate-500">
                      <AlertTriangle className="w-4 h-4 text-slate-400 shrink-0" />
                      <span>Hosting on shared servers</span>
                    </li>
                  </ul>
                </div>

                <div className="pt-6">
                  <a
                    href="https://aibizzhub.io/marketplace"
                    className="block text-center w-full py-2.5 rounded-lg border border-slate-300 hover:border-slate-800 bg-white hover:bg-slate-50 text-slate-900 font-semibold text-xs transition-all cursor-pointer shadow-xs"
                  >
                    Choose Sites Plan
                  </a>
                </div>
              </div>

              {/* Plan 2: Servers (Recommended Enterprise) */}
              <div className="rounded-2xl border-2 border-[#0066cc] bg-white p-6 sm:p-7 shadow-lg shadow-blue-500/10 transition-all flex flex-col justify-between relative">
                <div className="absolute -top-3 right-6 bg-[#0066cc] text-white text-[11px] font-bold uppercase tracking-wider px-3 py-0.5 rounded-full shadow-sm">
                  Recommended
                </div>

                <div>
                  <div className="flex items-center justify-between">
                    <h3 className="text-xl font-bold text-slate-900">Servers</h3>
                    <span className="text-[11px] font-semibold text-[#0066cc] bg-blue-50 px-2.5 py-0.5 rounded-full">Dedicated</span>
                  </div>
                  <p className="text-xs sm:text-sm text-slate-500 mt-1">
                    Get a virtual machine to host multiple sites and benches
                  </p>

                  <div className="mt-6 flex items-baseline gap-1">
                    <span className="text-3xl font-bold text-slate-900">$149</span>
                    <span className="text-xs text-slate-500 font-medium">onwards /mo</span>
                  </div>

                  <div className="mt-4 text-[11px] font-black text-red-600 tracking-wider">
                    HETZNER
                  </div>

                  {/* Checklist */}
                  <ul className="mt-6 space-y-3 text-xs sm:text-sm text-slate-600 border-t border-slate-100 pt-5">
                    <li className="flex items-center gap-2.5">
                      <Check className="w-4 h-4 text-[#0066cc] shrink-0" />
                      <span>Shared or Dedicated instances</span>
                    </li>
                    <li className="flex items-center gap-2.5">
                      <Check className="w-4 h-4 text-[#0066cc] shrink-0" />
                      <span>Unified or Separate App & DB</span>
                    </li>
                    <li className="flex items-center gap-2.5">
                      <Check className="w-4 h-4 text-[#0066cc] shrink-0" />
                      <span>Best price-performance ratio</span>
                    </li>
                    <li className="flex items-center gap-2.5 text-slate-500">
                      <AlertTriangle className="w-4 h-4 text-slate-400 shrink-0" />
                      <span>Limited uptime guarantees</span>
                    </li>
                    <li className="flex items-center gap-2.5 text-slate-500">
                      <AlertTriangle className="w-4 h-4 text-slate-400 shrink-0" />
                      <span>Only incident support</span>
                    </li>
                  </ul>

                  {/* Higher Tier within Servers */}
                  {/* <div className="mt-6 pt-5 border-t border-slate-100">
                    <div className="flex items-baseline gap-1">
                      <span className="text-2xl font-bold text-slate-900">$65</span>
                      <span className="text-xs text-slate-500 font-medium">onwards /mo</span>
                    </div>
                    <div className="flex items-center gap-3 mt-2 text-[11px] font-bold text-slate-500">
                      <span className="text-amber-600 font-black">aws</span>
                      <span className="text-rose-600 font-black">OCI</span>
                      <span className="text-blue-600 font-black">DigitalOcean</span>
                    </div>
                    <p className="text-xs text-slate-500 mt-2 font-medium">
                      Everything in Hetzner, plus
                    </p>
                  </div> */}
                </div>

                <div className="pt-6">
                  <a
                    href="https://aibizzhub.io/#pricing"
                    className="block text-center w-full py-2.5 rounded-lg bg-[#0066cc] hover:bg-[#0052a3] text-white font-semibold text-xs transition-all shadow-xs cursor-pointer"
                  >
                    Choose Server Plan
                  </a>
                </div>
              </div>

            </div>
          </div>
        </div>

        {/* STEP 2: Set up AiBizzApp */}
        <div className="relative pl-8 sm:pl-12 border-l-2 border-slate-200 pb-16">
          {/* Step 2 badge */}
          <div className="absolute -left-[17px] top-0 h-8 w-8 rounded-full bg-slate-100 border-2 border-slate-300 text-slate-700 flex items-center justify-center text-xs font-bold shadow-sm">
            2
          </div>

          <div>
            <span className="text-[11px] font-bold tracking-wider text-slate-400 uppercase">
              STEP 2
            </span>
            <h2 className="text-2xl font-medium text-slate-900 tracking-tight mt-1">
              Set up AiBizzApp
            </h2>
            <p className="mt-2 text-sm sm:text-base text-slate-600 leading-relaxed">
              Your choice of implementation model depends on cost and customisation preferences. You can pick any one of the following options.
            </p>

            {/* Option 1: Self-implement */}
            <div className="mt-8 space-y-2">
              <h3 className="text-base font-bold text-slate-900">Self-implement</h3>
              <p className="text-sm text-slate-600 leading-relaxed">
                If you are just starting out, try AiBizzApp on your own. Refer to the AiBizzApp documentation if you want to learn more or troubleshoot. Ideal for freelancers and DIY-enthusiasts.
              </p>
              <a
                href="#docs"
                className="inline-flex items-center gap-1.5 text-sm font-semibold text-slate-900 hover:text-blue-600 pt-1 transition-colors group"
              >
                <span>Read docs</span>
                <ArrowRight className="w-4 h-4 group-hover:translate-x-1 transition-transform" />
              </a>
            </div>

            {/* Divider OR */}
            <div className="relative my-8">
              <div className="absolute inset-0 flex items-center">
                <div className="w-full border-t border-slate-200" />
              </div>
              <div className="relative flex justify-center">
                <span className="bg-white px-3 text-xs font-semibold tracking-wider text-slate-400 uppercase">
                  OR
                </span>
              </div>
            </div>

            {/* Option 2: Starter Pack */}
            <div className="space-y-2">
              <h3 className="text-base font-bold text-slate-900">Go live with a Starter Pack</h3>
              <p className="text-sm text-slate-600 leading-relaxed">
                If you are just looking for some expert support to migrate from your current platform, go for Starter Packs. Our certified partners will help you get started quickly and economically.
              </p>
              <a
                href="#starter-packs"
                className="inline-flex items-center gap-1.5 text-sm font-semibold text-slate-900 hover:text-blue-600 pt-1 transition-colors group"
              >
                <span>Explore Starter Packs</span>
                <ArrowRight className="w-4 h-4 group-hover:translate-x-1 transition-transform" />
              </a>
            </div>

            {/* Divider OR */}
            <div className="relative my-8">
              <div className="absolute inset-0 flex items-center">
                <div className="w-full border-t border-slate-200" />
              </div>
              <div className="relative flex justify-center">
                <span className="bg-white px-3 text-xs font-semibold tracking-wider text-slate-400 uppercase">
                  OR
                </span>
              </div>
            </div>

            {/* Option 3: Pick a partner */}
            <div className="space-y-2">
              <h3 className="text-base font-bold text-slate-900">Pick a partner for implementation</h3>
              <p className="text-sm text-slate-600 leading-relaxed">
                Our global network of 200+ partners helps businesses implement our products smoothly. Our partners are trained and certified to ensure that customers get the best AiBizz experience. If your business requires help with <strong className="text-slate-900 font-semibold">setup, support, customisations, or integrations</strong>, we recommend reaching out to an AiBizz partner to help get you started.
              </p>
              <a
                href="#partners"
                className="inline-flex items-center gap-1.5 text-sm font-semibold text-slate-900 hover:text-blue-600 pt-1 transition-colors group"
              >
                <span>View all partners</span>
                <ArrowRight className="w-4 h-4 group-hover:translate-x-1 transition-transform" />
              </a>
            </div>

          </div>
        </div>

        {/* STEP 3 / COMPLETION: You're all set! */}
        <div className="relative pl-8 sm:pl-12 pb-16">
          {/* Checkmark icon badge */}
          <div className="absolute -left-[17px] top-0 h-8 w-8 rounded-full bg-slate-100 border-2 border-slate-300 text-slate-700 flex items-center justify-center shadow-sm">
            <Check className="w-4 h-4 text-emerald-600" />
          </div>

          <div>
            <span className="text-[11px] font-bold tracking-wider text-slate-400 uppercase">
              COMPLETION
            </span>
            <h2 className="text-2xl font-medium text-slate-900 tracking-tight mt-1">
              You're all set!
            </h2>
            <p className="mt-1 text-sm text-slate-600">
              Start your AiBizzApp journey now!
            </p>
          </div>
        </div>

        {/* FAQ Accordion Section matching screenshot 4 */}
        <div className="pt-8 border-t border-slate-200">
          <h2 className="text-2xl sm:text-3xl font-medium text-slate-900 tracking-tight mb-8">
            Frequently asked questions
          </h2>

          <div className="divide-y divide-slate-200 border-b border-slate-200">
            {faqs.map((faq, idx) => {
              const isOpen = openFaq === idx
              return (
                <div key={idx} className="py-4">
                  <button
                    onClick={() => toggleFaq(idx)}
                    className="w-full flex items-center justify-between text-left text-sm sm:text-base font-semibold text-slate-900 hover:text-blue-600 transition-colors cursor-pointer py-1"
                  >
                    <span>{faq.q}</span>
                    <span className="text-xl font-light text-slate-400 ml-4 shrink-0">
                      {isOpen ? '−' : '+'}
                    </span>
                  </button>

                  <AnimatePresence>
                    {isOpen && (
                      <motion.div
                        initial={{ opacity: 0, height: 0 }}
                        animate={{ opacity: 1, height: 'auto' }}
                        exit={{ opacity: 0, height: 0 }}
                        transition={{ duration: 0.2 }}
                        className="overflow-hidden"
                      >
                        <p className="text-sm text-slate-600 leading-relaxed pt-2 pb-2">
                          {faq.a}
                        </p>
                      </motion.div>
                    )}
                  </AnimatePresence>
                </div>
              )
            })}
          </div>
        </div>

        {/* Ready to switch to AiBizzApp? Contact us -> Card (Screenshot 2) */}
        <div className="mt-16 rounded-2xl border border-slate-200 bg-white p-6 sm:p-8 shadow-sm flex flex-col sm:flex-row items-center justify-between gap-4">
          <span className="text-base sm:text-lg font-bold text-slate-900 text-center sm:text-left">
            Ready to switch to AiBizzApp?
          </span>
          <button 
            onClick={() => {
              if (onNavigate) onNavigate('contact')
              window.scrollTo({ top: 0, behavior: 'smooth' })
            }}
            className="inline-flex items-center gap-2 px-5 py-2.5 rounded-xl bg-slate-100 hover:bg-slate-200 text-slate-900 text-sm font-medium transition-colors cursor-pointer"
          >
            <span>Contact us</span>
            <ArrowRight className="w-4 h-4" />
          </button>
        </div>

      </div>
    </div>
  )
}
